"""Sample recipe fixtures for tests and factories."""

SAMPLE_RECIPES = [
    {
        "name": "Creamy Mushroom Pasta",
        "cuisine": "Italian",
        "tags": ["Pasta", "Vegetarian", "Comfort Food"],
        "ingredients": [
            "Tagliatelle or fettuccine pasta",
            "Cremini mushrooms, sliced",
            "Garlic, minced",
            "Heavy cream",
            "Parmesan cheese, grated",
            "Fresh parsley, chopped",
            "Butter",
            "Olive oil",
            "Salt and black pepper",
            "Dry white wine (optional)",
        ],
        "instructions": [
            "Cook pasta in salted boiling water according to package instructions.",
            "In a large skillet, heat olive oil and butter over medium heat.",
            "Add sliced mushrooms and cook until golden brown.",
            "Add minced garlic and cook for 1 minute.",
            "Pour in white wine and let it reduce.",
            "Stir in heavy cream and simmer for 3-4 minutes.",
            "Add Parmesan and stir until sauce thickens.",
            "Toss pasta in sauce and season with salt and pepper.",
            "Garnish with fresh parsley before serving.",
        ],
        "mealType": ["Dinner"],
        "servings": 4,
        "difficulty": "Easy",
        "prepTimeMinutes": 10,
        "cookTimeMinutes": 15,
        "caloriesPerServing": 520,
        "rating": 4.8,
    },
    {
        "name": "Classic Margherita Pizza",
        "cuisine": "Italian",
        "tags": ["Pizza", "Vegetarian", "Classic"],
        "ingredients": [
            "Pizza dough",
            "Tomato sauce",
            "Fresh mozzarella",
            "Fresh basil leaves",
            "Olive oil",
            "Salt",
        ],
        "instructions": [
            "Preheat oven to 475°F (245°C).",
            "Roll out pizza dough on a floured surface.",
            "Spread tomato sauce evenly over dough.",
            "Add mozzarella slices.",
            "Drizzle with olive oil and sprinkle salt.",
            "Bake for 12-15 minutes until crust is golden.",
            "Top with fresh basil leaves before serving.",
        ],
        "mealType": ["Lunch", "Dinner"],
        "servings": 2,
        "difficulty": "Medium",
        "prepTimeMinutes": 20,
        "cookTimeMinutes": 15,
        "caloriesPerServing": 680,
        "rating": 4.9,
    },
    {
        "name": "Chicken Stir Fry",
        "cuisine": "Chinese",
        "tags": ["Chicken", "Quick", "Healthy"],
        "ingredients": [
            "Chicken breast, sliced",
            "Bell peppers",
            "Broccoli florets",
            "Soy sauce",
            "Garlic",
            "Ginger",
            "Sesame oil",
            "Cornstarch",
        ],
        "instructions": [
            "Marinate chicken in soy sauce and cornstarch.",
            "Heat oil in wok over high heat.",
            "Stir fry chicken until cooked through.",
            "Add vegetables and cook for 3-4 minutes.",
            "Add garlic and ginger.",
            "Drizzle with sesame oil and serve.",
        ],
        "mealType": ["Lunch", "Dinner"],
        "servings": 4,
        "difficulty": "Easy",
        "prepTimeMinutes": 15,
        "cookTimeMinutes": 10,
        "caloriesPerServing": 320,
        "rating": 4.5,
    },
]

