"""Sample recipe fixtures for tests and factories."""

SAMPLE_RECIPES = [
    {
        "name": "Creamy Mushroom Pasta",
        "cuisine": "Italian",
        "tags": ["Pasta", "Vegetarian", "Comfort Food"],
        "ingredients": [
            "Tagliatelle or fettuccine pasta",
            "Cremini mushrooms, sliced",
            "Garlic, minced",
            "Heavy cream",
            "Parmesan cheese, grated",
            "Fresh parsley, chopped",
            "Butter",
            "Olive oil",
            "Salt and black pepper",
            "Dry white wine (optional)",
        ],
        "instructions": [
            "Cook pasta in salted boiling water according to package instructions.",
            "In a large skillet, heat olive oil and butter over medium heat.",
            "Add sliced mushrooms and cook until golden brown.",
            "Add minced garlic and cook for 1 minute.",
            "Pour in white wine and let it reduce.",
            "Stir in heavy cream and simmer for 3-4 minutes.",
            "Add Parmesan and stir until sauce thickens.",
            "Toss pasta in sauce and season with salt and pepper.",
            "Garnish with fresh parsley before serving.",
        ],
        "mealType": ["Dinner"],
        "servings": 4,
        "difficulty": "Easy",
        "prepTimeMinutes": 10,
        "cookTimeMinutes": 15,
        "caloriesPerServing": 520,
        "rating": 4.8,
    },
    {
        "name": "Classic Margherita Pizza",
        "cuisine": "Italian",
        "tags": ["Pizza", "Vegetarian", "Classic"],
        "ingredients": [
            "Pizza dough",
            "Tomato sauce",
            "Fresh mozzarella",
            "Fresh basil leaves",
            "Olive oil",
            "Salt",
        ],
        "instructions": [
            "Preheat oven to 475°F (245°C).",
            "Roll out pizza dough on a floured surface.",
            "Spread tomato sauce evenly over dough.",
            "Add mozzarella slices.",
            "Drizzle with olive oil and sprinkle salt.",
            "Bake for 12-15 minutes until crust is golden.",
            "Top with fresh basil leaves before serving.",
        ],
        "mealType": ["Lunch", "Dinner"],
        "servings": 2,
        "difficulty": "Medium",
        "prepTimeMinutes": 20,
        "cookTimeMinutes": 15,
        "caloriesPerServing": 680,
        "rating": 4.9,
    },
    {
        "name": "Chicken Stir Fry",
        "cuisine": "Chinese",
        "tags": ["Chicken", "Quick", "Healthy"],
        "ingredients": [
            "Chicken breast, sliced",
            "Bell peppers",
            "Broccoli florets",
            "Soy sauce",
            "Garlic",
            "Ginger",
            "Sesame oil",
            "Cornstarch",
        ],
        "instructions": [
            "Marinate chicken in soy sauce and cornstarch.",
            "Heat oil in wok over high heat.",
            "Stir fry chicken until cooked through.",
            "Add vegetables and cook for 3-4 minutes.",
            "Add garlic and ginger.",
            "Drizzle with sesame oil and serve.",
        ],
        "mealType": ["Lunch", "Dinner"],
        "servings": 4,
        "difficulty": "Easy",
        "prepTimeMinutes": 15,
        "cookTimeMinutes": 10,
        "caloriesPerServing": 320,
        "rating": 4.5,
    },
    {
        "name": "Spicy Tacos",
        "cuisine": "Mexican",
        "tags": ["Tacos", "Spicy", "Quick"],
        "ingredients": [
            "Ground beef",
            "Taco shells",
            "Lettuce",
            "Tomatoes",
            "Cheddar cheese",
            "Sour cream",
            "Salsa",
            "Jalapeños",
        ],
        "instructions": [
            "Brown ground beef in a skillet.",
            "Add taco seasoning and water.",
            "Simmer for 10 minutes.",
            "Warm taco shells.",
            "Fill shells with beef and toppings.",
            "Serve with salsa and sour cream.",
        ],
        "mealType": ["Lunch", "Dinner"],
        "servings": 4,
        "difficulty": "Easy",
        "prepTimeMinutes": 10,
        "cookTimeMinutes": 15,
        "caloriesPerServing": 450,
        "rating": 4.3,
    },
    {
        "name": "Sushi Rolls",
        "cuisine": "Japanese",
        "tags": ["Sushi", "Raw Fish", "Advanced"],
        "ingredients": [
            "Sushi rice",
            "Nori sheets",
            "Fresh salmon",
            "Cucumber",
            "Avocado",
            "Rice vinegar",
            "Wasabi",
            "Soy sauce",
        ],
        "instructions": [
            "Season sushi rice with vinegar.",
            "Place nori on bamboo mat.",
            "Spread rice on nori.",
            "Add fillings in a line.",
            "Roll tightly using the mat.",
            "Cut into pieces and serve.",
        ],
        "mealType": ["Lunch", "Dinner"],
        "servings": 2,
        "difficulty": "Hard",
        "prepTimeMinutes": 30,
        "cookTimeMinutes": 5,
        "caloriesPerServing": 280,
        "rating": 4.7,
    },
    {
        "name": "Beef Bourguignon",
        "cuisine": "French",
        "tags": ["Beef", "Stew", "Gourmet"],
        "ingredients": [
            "Beef chuck",
            "Red wine",
            "Carrots",
            "Onions",
            "Mushrooms",
            "Tomato paste",
            "Beef broth",
            "Thyme",
        ],
        "instructions": [
            "Brown beef in a pot.",
            "Add vegetables and tomato paste.",
            "Pour in red wine and beef broth.",
            "Simmer for 2-3 hours on low heat.",
            "Add mushrooms in the last 30 minutes.",
            "Season and serve.",
        ],
        "mealType": ["Dinner"],
        "servings": 6,
        "difficulty": "Medium",
        "prepTimeMinutes": 20,
        "cookTimeMinutes": 180,
        "caloriesPerServing": 450,
        "rating": 4.9,
    },
    {
        "name": "Butter Chicken",
        "cuisine": "Indian",
        "tags": ["Chicken", "Curry", "Creamy"],
        "ingredients": [
            "Chicken breast",
            "Yogurt",
            "Butter",
            "Tomato sauce",
            "Heavy cream",
            "Garam masala",
            "Garlic",
            "Ginger",
        ],
        "instructions": [
            "Marinate chicken in yogurt and spices.",
            "Cook chicken in a skillet.",
            "Make butter sauce with tomato and cream.",
            "Add chicken to sauce.",
            "Simmer for 15-20 minutes.",
            "Serve with rice or naan.",
        ],
        "mealType": ["Dinner"],
        "servings": 4,
        "difficulty": "Medium",
        "prepTimeMinutes": 20,
        "cookTimeMinutes": 30,
        "caloriesPerServing": 380,
        "rating": 4.8,
    },
    {
        "name": "Pad Thai",
        "cuisine": "Thai",
        "tags": ["Noodles", "Shrimp", "Spicy"],
        "ingredients": [
            "Rice noodles",
            "Shrimp",
            "Peanuts",
            "Lime",
            "Fish sauce",
            "Egg",
            "Bean sprouts",
            "Green onions",
        ],
        "instructions": [
            "Soak rice noodles in water.",
            "Cook shrimp in oil.",
            "Add noodles and sauce ingredients.",
            "Stir fry quickly.",
            "Push to the side and scramble egg.",
            "Mix everything and serve.",
        ],
        "mealType": ["Lunch", "Dinner"],
        "servings": 4,
        "difficulty": "Easy",
        "prepTimeMinutes": 15,
        "cookTimeMinutes": 10,
        "caloriesPerServing": 340,
        "rating": 4.6,
    },
]

